spring:
  application:
    name: clinic-booking

  # ── DATABASE (Supabase) ───────────────────────────────────
  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.fxoegtmztqihxvuixksm
    password: 9Do4uAa5Y85jciTi
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USER:default}
      password: ${REDIS_PASSWORD:}

  # ── FLYWAY ───────────────────────────────────────────────
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # # ── MAIL ─────────────────────────────────────────────────
  # mail:
  #   host: smtp.sendgrid.net
  #   port: 587
  #   username: apikey
  #   password: 
  #   properties:
  #     mail.smtp.auth: true
  #     mail.smtp.starttls.enable: true

  # ── FILE UPLOAD ───────────────────────────────────────────
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080
  servlet:
    context-path: /api

# ── JWT ───────────────────────────────────────────────────
app:
  jwt:
    secret: "day-la-secret-key-cua-ban-phai-dai-hon-32-ky-tu-nhe"
    access-token-expiry-ms: 900000       # 15 phút
    refresh-token-expiry-ms: 604800000   # 7 ngày

  slot:
    hold-duration-minutes: 10

  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
      - http://localhost:52688
      - https://your-doctor-app.onrender.com

  cloudinary:
    cloud-name: 
    api-key: 
    api-secret: 

# ── SWAGGER ───────────────────────────────────────────────
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# ── ACTUATOR ──────────────────────────────────────────────
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
